/**
 * Pure helpers for summarising Chromium's `certificate-error` event
 * data into a renderer-friendly payload (issue #444). No Electron
 * imports — the helpers accept a structural subset of Electron's
 * `Certificate` type so they can be exercised under `node:test`
 * against real self-signed certs generated by Node's `crypto` /
 * `tls` modules.
 *
 * The summary feeds the Chrome-style interstitial:
 *
 *   1. `host` is what we show in the headline ("`<host>` uses an
 *      invalid security certificate").
 *   2. `errorCode` carries Chromium's identifier (`CERT_DATE_INVALID`
 *      etc.) so the renderer can pick a specific explanation.
 *   3. `errorDescription` is a one-line human-readable summary the
 *      interstitial can show without the renderer having to know
 *      every chromium error string.
 *   4. `fingerprint` is the value we key the exception store on, so
 *      a rotated cert re-triggers the warning.
 *   5. `validStart` / `validExpiry` / `issuerName` / `subjectName` are
 *      displayed in the "details" expander so the user has the
 *      basic facts without us shipping a full chain viewer.
 */

/**
 * Structural subset of Electron's `Certificate`. Defined here (rather
 * than importing from Electron) so the helper is testable under plain
 * `node:test` without an Electron runtime. The fields match the
 * shape Chromium hands us in the `certificate-error` event callback.
 */
export interface CertificateLike {
  /** Fingerprint, typically `"sha256/<hex>"`. */
  fingerprint: string;
  /** PEM-encoded leaf. Not surfaced to the renderer today, but kept
   *  in the type so a future "view cert" expander has the raw cert
   *  available. */
  data?: string;
  /** RFC 4514 subject string (e.g. `"CN=example.com,O=Acme"`). */
  subjectName?: string;
  /** RFC 4514 issuer string. Empty / equal to subject for
   *  self-signed certs. */
  issuerName?: string;
  /** Seconds since unix epoch. */
  validStart?: number;
  /** Seconds since unix epoch. */
  validExpiry?: number;
}

/**
 * Renderer-side payload. Pushed as the `browser-cert-error` event
 * and also returned from the `browser_get_cert_error_for_view` IPC so
 * a renderer that mounts after the event fired (e.g. after a reload
 * or an LRU eviction round-trip) can still draw the interstitial.
 *
 * `snake_case` is intentional — matches the convention used by every
 * other browser-pane IPC event in `shared/types.ts`.
 */
export interface BrowserCertErrorPayload {
  browser_id: string;
  workspace_id: string;
  /** The URL the user (or a redirect chain) was trying to load. */
  url: string;
  /** Lowercased hostname extracted from `url`. The interstitial
   *  shows this verbatim in the headline. */
  host: string;
  /** Chromium error code (e.g. `"CERT_DATE_INVALID"`,
   *  `"CERT_AUTHORITY_INVALID"`). */
  error_code: string;
  /** Human-readable explanation derived from `error_code`. The
   *  renderer uses this so it doesn't have to know every Chromium
   *  string. */
  error_description: string;
  /** Fingerprint of the offending cert, used as the exception-store
   *  key. */
  fingerprint: string;
  /** Subject string from the cert; optional because Chromium can
   *  sometimes hand us a malformed cert. */
  subject_name?: string;
  /** Issuer string; empty for self-signed in some Chromium builds. */
  issuer_name?: string;
  /** Validity window. Seconds since epoch, as Chromium reports them. */
  valid_start?: number;
  valid_expiry?: number;
}

/**
 * Extract the lowercased hostname from a URL. Returns `""` for
 * inputs that aren't parseable (e.g. `about:blank`) — the
 * interstitial then falls back to showing the raw URL.
 */
export function hostFromUrl(url: string): string {
  try {
    return new URL(url).hostname.toLowerCase();
  } catch {
    return "";
  }
}

/**
 * Map a Chromium cert-error code to a one-line, user-facing
 * explanation. Mirrors the prose Chrome's own interstitial uses for
 * the same error class. Returns the raw code when we don't have a
 * specific string — the interstitial will still show *something*
 * useful rather than crash on an unknown error.
 *
 * Chromium emits these codes via `net::ErrorToString` (see
 * `net/base/net_error_list.h`). The list below covers every common
 * cert-validation error Band browser tabs are likely to hit
 * (expired, self-signed, hostname mismatch, untrusted CA, revoked,
 * weak signature).
 */
export function describeCertError(errorCode: string): string {
  switch (errorCode) {
    case "net::ERR_CERT_DATE_INVALID":
    case "CERT_DATE_INVALID":
      return "The certificate has expired or is not yet valid.";
    case "net::ERR_CERT_AUTHORITY_INVALID":
    case "CERT_AUTHORITY_INVALID":
      return "The certificate is not trusted because the issuer is unknown (self-signed or issued by an unrecognised authority).";
    case "net::ERR_CERT_COMMON_NAME_INVALID":
    case "CERT_COMMON_NAME_INVALID":
      return "The certificate does not match the hostname of the site.";
    case "net::ERR_CERT_REVOKED":
    case "CERT_REVOKED":
      return "The certificate has been revoked by the issuer.";
    case "net::ERR_CERT_WEAK_SIGNATURE_ALGORITHM":
    case "CERT_WEAK_SIGNATURE_ALGORITHM":
      return "The certificate is signed with a weak algorithm (e.g. SHA-1).";
    case "net::ERR_CERT_WEAK_KEY":
    case "CERT_WEAK_KEY":
      return "The certificate uses a key that is too weak (e.g. <2048-bit RSA).";
    case "net::ERR_CERT_INVALID":
    case "CERT_INVALID":
      return "The certificate is malformed or otherwise invalid.";
    case "net::ERR_CERT_NO_REVOCATION_MECHANISM":
    case "CERT_NO_REVOCATION_MECHANISM":
      return "The certificate has no mechanism for checking whether it has been revoked.";
    case "net::ERR_CERT_NON_UNIQUE_NAME":
    case "CERT_NON_UNIQUE_NAME":
      return "The certificate is issued for a non-unique private hostname.";
    case "net::ERR_CERT_NAME_CONSTRAINT_VIOLATION":
    case "CERT_NAME_CONSTRAINT_VIOLATION":
      return "The certificate violates a name constraint imposed by its issuer.";
    case "net::ERR_CERT_SYMANTEC_LEGACY":
    case "CERT_SYMANTEC_LEGACY":
      return "The certificate was issued by a CA that is no longer trusted.";
    default:
      return `The certificate could not be verified (${errorCode}).`;
  }
}

/**
 * Build a renderer-facing payload from the raw arguments Chromium hands
 * the `certificate-error` event. Caller provides the LRU `key` so the
 * payload can be filtered to the right tab — both `browser_id` and
 * `workspace_id` are set to the same value to match the existing
 * dual-key convention in `view-manager.ts::wireEvents`.
 */
export function buildCertErrorPayload(args: {
  key: string;
  url: string;
  errorCode: string;
  certificate: CertificateLike;
}): BrowserCertErrorPayload {
  const host = hostFromUrl(args.url);
  return {
    browser_id: args.key,
    workspace_id: args.key,
    url: args.url,
    host,
    error_code: args.errorCode,
    error_description: describeCertError(args.errorCode),
    fingerprint: args.certificate.fingerprint,
    subject_name: args.certificate.subjectName,
    issuer_name: args.certificate.issuerName,
    valid_start: args.certificate.validStart,
    valid_expiry: args.certificate.validExpiry,
  };
}
