/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorktreeWorktreeIdRouteImport } from './routes/worktree.$worktreeId'
import { Route as TaskTaskIdRouteImport } from './routes/task.$taskId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorktreeWorktreeIdRoute = WorktreeWorktreeIdRouteImport.update({
  id: '/worktree/$worktreeId',
  path: '/worktree/$worktreeId',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskTaskIdRoute = TaskTaskIdRouteImport.update({
  id: '/task/$taskId',
  path: '/task/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/task/$taskId': typeof TaskTaskIdRoute
  '/worktree/$worktreeId': typeof WorktreeWorktreeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/task/$taskId': typeof TaskTaskIdRoute
  '/worktree/$worktreeId': typeof WorktreeWorktreeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/task/$taskId': typeof TaskTaskIdRoute
  '/worktree/$worktreeId': typeof WorktreeWorktreeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/task/$taskId' | '/worktree/$worktreeId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/task/$taskId' | '/worktree/$worktreeId'
  id: '__root__' | '/' | '/task/$taskId' | '/worktree/$worktreeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TaskTaskIdRoute: typeof TaskTaskIdRoute
  WorktreeWorktreeIdRoute: typeof WorktreeWorktreeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worktree/$worktreeId': {
      id: '/worktree/$worktreeId'
      path: '/worktree/$worktreeId'
      fullPath: '/worktree/$worktreeId'
      preLoaderRoute: typeof WorktreeWorktreeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task/$taskId': {
      id: '/task/$taskId'
      path: '/task/$taskId'
      fullPath: '/task/$taskId'
      preLoaderRoute: typeof TaskTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TaskTaskIdRoute: TaskTaskIdRoute,
  WorktreeWorktreeIdRoute: WorktreeWorktreeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
