import { createLogger } from "@band-app/logger";
import { getBrowser } from "./browser-manager";

const log = createLogger("browser-host");

// ---------------------------------------------------------------------------
// CDP screencast experiment — server-side Browser Host state
//
// Lives in the infra tier so the CDP adapters that sit next to it
// (`cdp-proxy.ts`, `cdp-targets.ts`) can import it without crossing back up
// to the services tier; the services-tier `BrowserHostService` wraps this
// module for router consumption. Moved from `lib/browser-host.ts` as part
// of the Phase 7.5 migration (issue #517).
//
// Note: this module imports `getBrowser` from the sibling
// `browser-manager` in the same infra/browser-host/ directory. The
// browser-manager itself is a thin back-compat shim around
// `services/browser-service` — kept colocated here so the CDP adapters
// can resolve a Band tab id to its browser metadata without crossing
// back up to the services tier.
//
// The web client and the agent address browser tabs by Band's persistent
// `browser_<uuid>` id (bandTabId). To actually drive a tab over CDP we need
// the tab's chromium target id (cdpTargetId), which is generated by the
// desktop's Electron at WebContentsView construction time.
//
// This module owns the transient bandTabId → cdpTargetId mapping and the
// "ensure a view exists" protocol. The desktop's React subscribes to the
// `ensureView` event stream below and translates each event into an IPC
// call to `BrowserViewManager.ensure()` (create-or-return-existing). It
// reports the resulting cdpTargetId back via the tRPC mutation
// `browserHost.targetReady` (which calls `resolveTargetReady`).
//
// On view destroy (LRU eviction, explicit close, desktop quit), the
// desktop reports via `markTargetDestroyed`, which clears the cache so the
// next access triggers a fresh ensure.
//
// All identifiers in the public API are bandTabIds. cdpTargetId never
// leaves this module — clients just hand us a bandTabId and trust the
// resolver.
// ---------------------------------------------------------------------------

/** Hardcoded CDP host/port that the desktop exposes via Electron's
 *  `--remote-debugging-port=9223` switch (set in apps/desktop/src/main/index.ts).
 *  Kept here so the proxy can build upstream URLs given a cdpTargetId. */
export const DESKTOP_CDP_HOST = "127.0.0.1";
export const DESKTOP_CDP_PORT = 9223;

export interface EnsureViewEvent {
  bandTabId: string;
  workspaceId: string;
  url: string;
}

type EnsureListener = (event: EnsureViewEvent) => void;

interface PendingEnsure {
  promise: Promise<string>;
  resolve: (id: string) => void;
  reject: (err: Error) => void;
  timeoutId: ReturnType<typeof setTimeout>;
}

// ---------------------------------------------------------------------------
// State (globalThis-backed so it survives Vite SSR HMR module reloads)
//
// Vite's dev plugin captures the tRPC `appRouter` at server boot for its WS
// subscription handler. When this module is edited, Vite hands fresh copies
// to HTTP route handlers (which use `ssrLoadModule` per request) but the
// captured WS handler keeps using the stale module. Without the
// globalThis-backed state, the desktop's bridge subscribes against the
// stale module's `ensureListeners` while `isDesktopHostConnected()` (called
// from a fresh module via the HTTP route) reads an empty Set, and the web
// always renders the "Open the desktop app" fallback.
// ---------------------------------------------------------------------------

interface SharedState {
  targetIdByBandTabId: Map<string, string>;
  pendingEnsures: Map<string, PendingEnsure>;
  ensureListeners: Set<EnsureListener>;
}

// biome-ignore lint/suspicious/noExplicitAny: globalThis stash for HMR survival
const globalAny = globalThis as any;
let shared: SharedState | undefined = globalAny.__bandBrowserHostState;
if (!shared) {
  shared = {
    targetIdByBandTabId: new Map<string, string>(),
    pendingEnsures: new Map<string, PendingEnsure>(),
    ensureListeners: new Set<EnsureListener>(),
  };
  globalAny.__bandBrowserHostState = shared;
}

/** bandTabId → cdpTargetId. Populated lazily; cleared on view destroy. */
const targetIdByBandTabId = shared.targetIdByBandTabId;

/** bandTabId → in-flight ensure promise, so concurrent requests for the
 *  same tab dedup to a single IPC roundtrip. */
const pendingEnsures = shared.pendingEnsures;

/** Subscribers to ensureView events (the desktop's React subscription). */
const ensureListeners = shared.ensureListeners;

const ENSURE_TIMEOUT_MS = 10_000;

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Resolve the current cdpTargetId for a Band browser tab, asking the
 * desktop to create the underlying WebContentsView if it doesn't exist
 * yet. Throws if no desktop subscriber is connected, or if the desktop
 * doesn't respond within the timeout.
 */
export async function ensureCdpTargetId(bandTabId: string): Promise<string> {
  const cached = targetIdByBandTabId.get(bandTabId);
  if (cached) return cached;

  // Dedup concurrent requests for the same tab.
  const inflight = pendingEnsures.get(bandTabId);
  if (inflight) return inflight.promise;

  const tab = getBrowser(bandTabId);
  if (!tab) {
    throw new Error(`Unknown Band browser tab: ${bandTabId}`);
  }

  if (ensureListeners.size === 0) {
    throw new Error(
      "Band desktop app is not connected — open the desktop app to use the Browser pane.",
    );
  }

  let resolveFn: (id: string) => void = () => {};
  let rejectFn: (err: Error) => void = () => {};
  const promise = new Promise<string>((resolve, reject) => {
    resolveFn = resolve;
    rejectFn = reject;
  });

  const timeoutId = setTimeout(() => {
    pendingEnsures.delete(bandTabId);
    rejectFn(
      new Error(`Timed out waiting for desktop to create a WebContentsView for ${bandTabId}`),
    );
  }, ENSURE_TIMEOUT_MS);

  pendingEnsures.set(bandTabId, {
    promise,
    resolve: resolveFn,
    reject: rejectFn,
    timeoutId,
  });

  log.info(
    "ensureCdpTargetId emitting ensureView for %s (url=%s, listeners=%d)",
    bandTabId,
    tab.url,
    ensureListeners.size,
  );
  for (const listener of ensureListeners) {
    try {
      listener({
        bandTabId,
        workspaceId: tab.workspaceId,
        url: tab.url,
      });
    } catch (err) {
      log.warn("ensureView listener threw: %s", err instanceof Error ? err.message : err);
    }
  }

  return promise;
}

/**
 * Called by the desktop (via `browserHost.targetReady` mutation) to
 * report that a WebContentsView is ready and provide its cdpTargetId.
 */
export function resolveTargetReady(bandTabId: string, cdpTargetId: string): void {
  log.info("resolveTargetReady %s → %s", bandTabId, cdpTargetId);
  targetIdByBandTabId.set(bandTabId, cdpTargetId);
  const pending = pendingEnsures.get(bandTabId);
  if (pending) {
    clearTimeout(pending.timeoutId);
    pendingEnsures.delete(bandTabId);
    pending.resolve(cdpTargetId);
  }
}

/**
 * Called by the desktop (via `browserHost.viewDestroyed` mutation) to
 * report that a WebContentsView was destroyed (LRU eviction, explicit
 * close). Clears the cached mapping so the next access triggers a fresh
 * ensure.
 */
export function markTargetDestroyed(bandTabId: string): void {
  log.info("markTargetDestroyed %s", bandTabId);
  targetIdByBandTabId.delete(bandTabId);
  const pending = pendingEnsures.get(bandTabId);
  if (pending) {
    clearTimeout(pending.timeoutId);
    pendingEnsures.delete(bandTabId);
    pending.reject(new Error(`View destroyed before ensure resolved (${bandTabId})`));
  }
}

/**
 * Subscribe to ensureView requests. The desktop's React calls this once
 * its tRPC subscription is active. Returns an unsubscribe.
 */
export function onEnsureView(listener: EnsureListener): () => void {
  ensureListeners.add(listener);
  log.info("onEnsureView subscriber added (total=%d)", ensureListeners.size);
  return () => {
    ensureListeners.delete(listener);
    log.info("onEnsureView subscriber removed (total=%d)", ensureListeners.size);
    // If the last subscriber goes away, fail in-flight ensures so callers
    // surface a clear "desktop disconnected" error instead of timing out,
    // and clear the cache (its targetIds are now stale).
    if (ensureListeners.size === 0) {
      for (const [bandTabId, pending] of pendingEnsures) {
        clearTimeout(pending.timeoutId);
        pending.reject(new Error("Band desktop disconnected during ensure"));
        pendingEnsures.delete(bandTabId);
      }
      targetIdByBandTabId.clear();
    }
  };
}

/** Whether any desktop client is currently subscribed. Used by the
 *  /api/cdp/tabs route to choose between the friendly "open the desktop
 *  app" error and a normal response. */
export function isDesktopHostConnected(): boolean {
  return ensureListeners.size > 0;
}
